import { AbpHttpInterceptor, RefreshTokenService, AbpHttpConfigurationService } from 'abp-ng2-module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';
import { ZeroTemplateHttpConfigurationService } from './zero-template-http-configuration.service';

@NgModule({
    providers: [
        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        // ApiServiceProxies.WebhookEventServiceProxy,
        // ApiServiceProxies.WebhookSubscriptionServiceProxy,
        // ApiServiceProxies.WebhookSendAttemptServiceProxy,
        ApiServiceProxies.UserDelegationServiceProxy,
        ApiServiceProxies.DynamicPropertyServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyDefinitionServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyServiceProxy,
        ApiServiceProxies.DynamicPropertyValueServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyValueServiceProxy,
        ApiServiceProxies.TwitterServiceProxy,
        // ApiServiceProxies.ManufacturerServiceProxy,
        // ApiServiceProxies.SupplierServiceProxy,
        // ApiServiceProxies.IntentRequestFormServiceProxy ,
        // ApiServiceProxies.UnitServiceProxy,
        // ApiServiceProxies.WareHouseServiceProxy,
        // ApiServiceProxies.DivisionServiceProxy,
        // ApiServiceProxies.BrigadeServiceProxy,
        // ApiServiceProxies.ItemServiceProxy,
        // ApiServiceProxies.RequestedItemServiceProxy,
        // ApiServiceProxies.StoreReleaseServiceProxy,
        // ApiServiceProxies.StoreReleaseDispatchServiceProxy,
        // ApiServiceProxies.IssueRequestServiceProxy,
        // ApiServiceProxies.LowLevelWareHouseItemServiceProxy,
        // ApiServiceProxies.RequestAuthorityFormServiceProxy,
        // ApiServiceProxies.LowLevelItemServiceProxy ,
        // ApiServiceProxies.ItemCategoryServiceProxy,
        // ApiServiceProxies.IssueRequestServiceProxy ,
        // ApiServiceProxies.ItemServiceProxy,
        // ApiServiceProxies.IssueProvisionServiceProxy,
        // ApiServiceProxies.EqisCommentServiceProxy,
        // ApiServiceProxies.EqisRemarkServiceProxy,
        // ApiServiceProxies.EqisNoteServiceProxy,
        // ApiServiceProxies.ApprovalServiceProxy,
        // ApiServiceProxies.VariationItemServiceProxy,
        // ApiServiceProxies.EncryptionkeyServiceProxy,
        // ApiServiceProxies.ItemTypeServiceProxy,
        // ApiServiceProxies.FileUploadServiceProxy,

        // ApiServiceProxies.ManufacturerServiceProxy,
        // ApiServiceProxies.SupplierServiceProxy,
        // ApiServiceProxies.ItemTypeServiceProxy,
        // ApiServiceProxies.EncryptionkeyServiceProxy,
        // ApiServiceProxies.VarietyBatchServiceProxy,
        // ApiServiceProxies.VarietyServiceProxy,
        // ApiServiceProxies.VarietyCategoryServiceProxy,
        ApiServiceProxies.DeviceServiceProxy,
        // ApiServiceProxies.StoreHouseAccessAuditLogServiceProxy,
        // ApiServiceProxies.StoreHouseAccessRequestServiceProxy,
        // ApiServiceProxies.AntennaWarehouseServiceProxy,
        // ApiServiceProxies.DeviceModelServiceProxy,
        // ApiServiceProxies.StoreHouseLockActivityServiceProxy,
        // ApiServiceProxies.DeviceAntennaServiceProxy,
        // ApiServiceProxies.ItemsTypesServiceProxy,
        // ApiServiceProxies.ItemCategoriesServiceProxy,
        // ApiServiceProxies.DeviceGpoConfigServiceProxy,
        // ApiServiceProxies.ApprovalStagesLevelServiceProxy,
        // ApiServiceProxies.StoreHouseAccessConfigServiceProxy,
        // ApiServiceProxies.RackServiceProxy,
        // ApiServiceProxies.RackCompartmentServiceProxy,
        // ApiServiceProxies.StoreHouseAccessDeviceStatusServiceProxy,
        // ApiServiceProxies.StoreHouseAccessAuditLogServiceProxy,
        // ApiServiceProxies.WareHouseAssignedDeviceServiceProxy,
        // ApiServiceProxies.CandidateServiceProxy,
        // ApiServiceProxies.CandidateCategoryServiceProxy,
        // ApiServiceProxies.StoreReleaseConfirmationServiceProxy,
        // ApiServiceProxies.CandidateInerviewLocationServiceProxy,
        // ApiServiceProxies.StoreDeliveryReceiptServiceProxy,
        // ApiServiceProxies.RankServiceProxy,
        // ApiServiceProxies.CandidatePrintServiceProxy,
         ApiServiceProxies.ElectionCountryServiceProxy,
         ApiServiceProxies.ElectionStateServiceProxy,
         ApiServiceProxies.ElectionSenatorialDistrictCouncilServiceProxy,
         ApiServiceProxies.ElectionFederalRepresentativeServiceProxy,
         ApiServiceProxies.ElectionAssemblyAreaServiceProxy,
         ApiServiceProxies.ElectionLocalCouncilServiceProxy,
         ApiServiceProxies.ElectionPostServiceProxy,
         ApiServiceProxies.ElectionWardServiceProxy,
         ApiServiceProxies.ElectionPollingUnitServiceProxy,
         ApiServiceProxies.ElectionAgentUserServiceProxy,
         ApiServiceProxies.ElectionPollingUnitResultServiceProxy,
         ApiServiceProxies.PoliticalPartyServiceProxy,
         ApiServiceProxies.ElectionCandidateServiceProxy,
         ApiServiceProxies.ElectionCandidateResultServiceProxy,
         ApiServiceProxies.ElectionGalleryServiceProxy,
         ApiServiceProxies.DeviceLocationTrackingActivityServiceProxy,
        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: AbpHttpConfigurationService, useClass: ZeroTemplateHttpConfigurationService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true }
    ]
})
export class ServiceProxyModule { }
